/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   exec_func_tools.c                                  :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: siun <siun@student.42.fr>                  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/11/22 18:05:19 by subpark           #+#    #+#             */
/*   Updated: 2023/12/03 23:35:19 by siun             ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../include/minishell.h"

char	*command_path(char **path_array, int i, char *command)
{
	char	*part_path;
	char	*path;

	part_path = ft_strjoin(path_array[i], "/");
	path = ft_strjoin(part_path, command);
	free(part_path);
	return (path);
}

char	*path_pointer(char **envp, char *command)
{
	char	*path;
	int		i;

	i = 0;
	while (envp[i] != NULL)
	{
		path = command_path(envp, i, command);
		if (access(path, F_OK) == 0 && access(path, X_OK) == 0)
			return (path);
		free(path);
		i ++;
	}
	return (NULL);
}

void	exec(char **cmd, char **env)
{
	char	*path;

	if (!cmd || !cmd[0])
		exit(0);
	path = path_pointer(env, cmd[0]);
	if (!path)
		exit(2);
	execve(path, cmd, env);
	if (path)
		free(path);
	exit (errno);
}

/*
if you are comparing only characters
use single quotes instead of double quotes
' ' instead of " "
*/
int	redirect_type(t_cmd *node)
{
	if (ft_strcmp(node->cmdstr[0], "<"))
		return (REL_TYPE_L);
	else if (ft_strcmp(node->cmdstr[0], "<<"))
		return (REL_TYPE_LL);
	else if (ft_strcmp(node->cmdstr[0], ">"))
		return (REL_TYPE_R);
	else if (ft_strcmp(node->cmdstr[0], ">>"))
		return (REL_TYPE_RR);
	return (0);
}

/*
command_path:
for the path_pointer check whether that command is exist or not(as a file),
make command as a type of path.
it can be existing/non-existing path.

path_pointer:
function that returns path of command exist.
from the path generated by command_path,
*/